FROM debian

RUN apt update && apt upgrade -y
RUN apt install nginx -y
RUN mkdir -p /etc/nginx/ssl
RUN apt install openssl -y
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=PACA/L=Nice/O=42/OU=42/CN=abtouait.42.fr/UID=abtouait"
RUN mkdir -p /var/run/nginx

EXPOSE 80

#desactive le daemon pour garder le processus nginx en vie
CMD ["nginx", "-g", "daemon off;"]